version: "3.9"
services:
  web:
    build: .
    image: bruno15/tests:latest
    ports:
        - '8080:80'
        - '8081:443'
    expose:
        - '8080'
        - '8081'
    volumes:
        - html_files:/var/www/html
    depends_on:
        - mysql
        - mysqlserver
    links:
        - mysql
        - mysqlserver
    environment:
        - VIRTUAL_HOST=test_host

  mysql:
    container_name: mysql_test
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
        - mysql_data:/var/lib/mysql

    environment:
        MYSQL_DATABASE: test_db
        MYSQL_ROOT_PASSWORD: root
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    ports:
        - '3307:3306'
        

  mysqlserver:
      
    
volumes:
    html_files:
    mysql_data: